services:
  # Grafana
  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    deploy:
      resources:
        limits:
          memory: 100M
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning/:/etc/grafana/provisioning/
    ports:
      - "${GRAFANA_SERVICE_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"